language: go

go:
  - 1.11

services:
  - docker

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/lint/golint
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
  - chmod +x get_helm.sh
  - ./get_helm.sh

before_script:
  - hack/verify-gofmt.sh
  - hack/verify-govet.sh
  - hack/verify-golint.sh
  - dep ensure
  - helm lint helm/botkube

script:
  - make 

after_success:
  - if [[ "$TRAVIS_BRANCH" == "develop" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push infracloud/botkube:latest;
    fi
