[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.4.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  branch = "master"
  name = "k8s.io/api"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[prune]
  go-tests = true
  unused-packages = true
