{{- if .Values.config.ssl.cert }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botkube.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ca-certificates.crt: {{ .Files.Get (printf "%s" .Values.config.ssl.cert) | b64enc }}

{{ end }}
